# Generated by Django 5.1.1 on 2024-10-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_usuario', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('acerca_de', models.TextField()),
                ('_contraseña', models.CharField(max_length=64)),
                ('_verificado', models.BooleanField(default=False)),
                ('_sin_leer', models.IntegerField(default=1)),
                ('_token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_publicacion', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('upvotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('logo', models.TextField()),
                ('integracion', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('cargo', models.CharField(max_length=255)),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('nick', models.JSONField(blank=True, null=True)),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='_publicaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_usuario', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='_siguiendo',
            field=models.ManyToManyField(related_name='seguidores', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='publicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_principal', models.CharField(max_length=255)),
                ('descripcion_rapida', models.TextField()),
                ('titulo', models.TextField()),
                ('publicacion_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_asociadas', to='core.publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='redes_sociales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redes_usuario', to='core.redsocial'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(auto_now=True)),
                ('contenido', models.TextField()),
                ('upvotes', models.IntegerField()),
                ('usuario_publicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='respuestas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_publicacion', to='core.respuesta'),
        ),
        migrations.CreateModel(
            name='SubForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('publicaciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_subforo', to='core.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('subpaginas', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('destacados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_juego', to='core.noticia')),
                ('redes_sociales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redes_juego', to='core.redsocial')),
                ('subforos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subforos_juego', to='core.subforo')),
            ],
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('permisos', models.JSONField(blank=True, null=True)),
                ('juegos_asociados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juegos_asociados', to='core.juego')),
            ],
            bases=('core.usuario',),
        ),
    ]
